-- Migration 001: schema v1 for idea-finder.
--
-- Tables: source, raw_post, pain, cluster, score, run, prompt_version,
-- llm_provider plus the schema_migrations bookkeeping table. All row IDs are
-- UUIDv7 generated by the database (uuid_generate_v7() below). Vectors are
-- pgvector columns with an ivfflat index for cosine similarity search.
--
-- Idempotent: safe to apply twice (CREATE EXTENSION IF NOT EXISTS,
-- CREATE TABLE IF NOT EXISTS, ...); the runner in db/migrate.py records the
-- applied version, so re-execution is a no-op by design.

-- pgvector is bundled with the pgserver postgres binaries (verified: PG16
-- ships vector 0.6.x). Required for pain.embedding and ivfflat search.
CREATE EXTENSION IF NOT EXISTS vector;

-- ---------------------------------------------------------------------------
-- UUIDv7 generation
-- ---------------------------------------------------------------------------

-- Postgres 16 has no native uuidv7(); derive it from gen_random_uuid():
-- take the v4 UUID's 16 random bytes, overwrite the top 6 bytes with the
-- 48-bit unix-millisecond timestamp, then stamp version 7 (RFC 9562) and the
-- 10xx variant. Result: time-ordered UUIDv7, pure SQL, no extension needed.
CREATE OR REPLACE FUNCTION uuid_generate_v7() RETURNS uuid AS $$
DECLARE
    bytes     bytea;
    unix_ts_ms bigint;
BEGIN
    unix_ts_ms := (extract(epoch FROM clock_timestamp()) * 1000)::bigint;
    bytes := decode(replace(gen_random_uuid()::text, '-', ''), 'hex');
    FOR i IN 0 .. 5 LOOP
        bytes := set_byte(bytes, i, ((unix_ts_ms >> ((5 - i) * 8)) & 255)::int);
    END LOOP;
    -- version 7: high nibble of byte 6
    bytes := set_byte(bytes, 6, (7 << 4) | (get_byte(bytes, 6) & 15));
    -- variant 10: two high bits of byte 8
    bytes := set_byte(bytes, 8, (2 << 6) | (get_byte(bytes, 8) & 63));
    RETURN encode(bytes, 'hex')::uuid;
END
$$ LANGUAGE plpgsql VOLATILE;
COMMENT ON FUNCTION uuid_generate_v7() IS
    'UUIDv7 (RFC 9562): 48-bit unix-ms timestamp + random payload, time-ordered';

-- Merge integer counters into a run's stats_json: existing keys accumulate,
-- new keys are added. Used by db/repo.update_run_stage for stats deltas.
CREATE OR REPLACE FUNCTION _stats_merge(stats jsonb, delta jsonb)
RETURNS jsonb AS $$
    SELECT coalesce(
        (SELECT jsonb_object_agg(key, val) FROM (
            -- existing keys: numbers accumulate, others keep the stored value
            SELECT s.key,
                   CASE WHEN jsonb_typeof(s.value) = 'number'
                        THEN to_jsonb(s.value::numeric + COALESCE((d.value #>> '{}')::numeric, 0))
                        ELSE s.value END AS val
            FROM jsonb_each(stats) s
            LEFT JOIN jsonb_each(delta) d ON d.key = s.key
            UNION ALL
            -- new keys from the delta
            SELECT d.key, d.value FROM jsonb_each(delta) d
            WHERE NOT EXISTS (SELECT 1 FROM jsonb_each(stats) s WHERE s.key = d.key)
        ) merged),
        '{}'::jsonb
    );
$$ LANGUAGE sql;

-- ---------------------------------------------------------------------------
-- Migration bookkeeping (applied by db/migrate.py)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS schema_migrations (
    version    integer PRIMARY KEY,
    applied_at timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- Sources: the platforms we harvest (fl.ru, Habr, Google Play, ...)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS source (
    id         uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
    name       text NOT NULL UNIQUE,
    created_at timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- Raw posts: everything collected, deduplicated by canonical URL
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS raw_post (
    id            uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
    source_id     uuid NOT NULL REFERENCES source(id),
    url_canon     text NOT NULL UNIQUE,
    url           text NOT NULL,
    title         text NOT NULL DEFAULT '',
    body          text NOT NULL DEFAULT '',
    kind          text NOT NULL CHECK (kind IN ('demand', 'complaint', 'discussion')),
    published_at  timestamptz,
    fetch_status  text NOT NULL DEFAULT 'new' CHECK (fetch_status IN ('new', 'fetched', 'failed')),
    suspect_short boolean NOT NULL DEFAULT false,
    created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_raw_post_source_id ON raw_post (source_id);
-- Extract stage picks the oldest unfetched posts first; stable scan order.
CREATE INDEX IF NOT EXISTS idx_raw_post_fetch_status ON raw_post (fetch_status, created_at);
CREATE INDEX IF NOT EXISTS idx_raw_post_kind ON raw_post (kind);

-- ---------------------------------------------------------------------------
-- Prompt versions: reproducible LLM prompts (file or UI origin)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS prompt_version (
    id         uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
    name       text NOT NULL,
    version    integer NOT NULL CHECK (version >= 1),
    body       text NOT NULL,
    source     text NOT NULL CHECK (source IN ('file', 'ui')),
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (name, version)
);

-- ---------------------------------------------------------------------------
-- Pains: LLM-extracted pains, each grounded in a verbatim quote
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS pain (
    id                 uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
    raw_post_id        uuid NOT NULL REFERENCES raw_post(id),
    body               text NOT NULL,
    audience           text NOT NULL DEFAULT '',
    quote              text NOT NULL,
    embedding          vector(384),           -- multilingual-e5-small output dim
    cluster_id         uuid,                  -- NULL until the cluster stage assigns it
    prompt_version_id  uuid NOT NULL REFERENCES prompt_version(id),
    created_at         timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_pain_raw_post_id ON pain (raw_post_id);
CREATE INDEX IF NOT EXISTS idx_pain_cluster_id ON pain (cluster_id);
CREATE INDEX IF NOT EXISTS idx_pain_prompt_version_id ON pain (prompt_version_id);
-- Cosine ANN index for near-duplicate pain detection during clustering.
-- Requires vector extension; safe on an empty table (ivfflat allows it).
CREATE INDEX IF NOT EXISTS idx_pain_embedding_ivfflat
    ON pain USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);

-- ---------------------------------------------------------------------------
-- Clusters: groups of semantically similar pains
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS cluster (
    id         uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
    title      text NOT NULL,
    size       integer NOT NULL DEFAULT 0 CHECK (size >= 0),
    kind_mix   jsonb NOT NULL DEFAULT '{}'::jsonb,  -- {"demand": 4, "complaint": 1}
    created_at timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- Scores: rubric-based assessment of a cluster
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS score (
    id           uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
    cluster_id   uuid NOT NULL UNIQUE REFERENCES cluster(id),
    total        numeric(5, 2) NOT NULL CHECK (total >= 0 AND total <= 10),
    rationale_md text NOT NULL DEFAULT '',
    quotes_json  jsonb NOT NULL DEFAULT '[]'::jsonb,  -- verbatim grounding quotes
    created_at   timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- Runs: pipeline executions; stages write progress here
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS run (
    id         uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
    started_at timestamptz NOT NULL DEFAULT now(),
    finished_at timestamptz,
    stages_json jsonb NOT NULL DEFAULT '{}'::jsonb,  -- {"collect": "done", ...}
    stats_json  jsonb NOT NULL DEFAULT '{}'::jsonb,  -- {"bricked": 0, ...}
    cost       numeric(10, 4) NOT NULL DEFAULT 0
);

-- ---------------------------------------------------------------------------
-- LLM providers: registry for the OpenAI-compatible client factory
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS llm_provider (
    id         uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
    name       text NOT NULL UNIQUE,
    kind       text NOT NULL CHECK (kind IN ('openai_compat', 'fake')),
    base_url   text NOT NULL DEFAULT '',
    model      text NOT NULL DEFAULT '',
    api_key    text NOT NULL DEFAULT '',  -- lives ONLY here, never in .env/code
    is_active  boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now()
);

-- Exactly one active provider at any time: a partial unique index makes a
-- second active row impossible at the constraint level (repo flips the old
-- active row in the same transaction).
CREATE UNIQUE INDEX IF NOT EXISTS uq_llm_provider_single_active
    ON llm_provider ((1)) WHERE is_active;
