"""All database writes and reads for idea-finder go through this module.

Stages never touch SQL themselves: they call these functions, which own the
idempotency guarantees (canonical-URL dedup, ON CONFLICT clauses, single
active LLM provider). Connections are injectable for tests; production code
passes a connection opened via ``bootstrap_pgserver.ensure_pgserver()``.

UUIDv7 row IDs are generated by the database (``uuid_generate_v7()``,
migration 001), so insert functions never specify ``id``.

Usage (smoke test)::

    python -m idea_finder.db.repo [data_dir]
"""

from __future__ import annotations

import json
import logging
import sys
from collections.abc import Sequence
from dataclasses import dataclass
from decimal import Decimal
from pathlib import Path
from typing import LiteralString, cast

from psycopg import Connection

from idea_finder.core.models import Pain, RawPost, Run, Score

logger = logging.getLogger(__name__)

__all__ = [
    "ClusterInputPain",
    "ClusterScoreInput",
    "LlmProviderRecord",
    "RepoError",
    "assign_pain_cluster",
    "create_run",
    "ensure_source",
    "finish_run",
    "get_active_llm_provider",
    "insert_pain",
    "insert_raw_post",
    "insert_score",
    "list_cluster_input_pains",
    "list_clusters_without_score",
    "list_enabled_sources",
    "list_posts_pending_extract",
    "reset_cluster_assignment",
    "set_raw_post_fetch_status",
    "table_counts",
    "update_cluster_stats",
    "update_pain_embedding",
    "update_run_stage",
    "upsert_cluster",
    "upsert_llm_provider",
    "upsert_prompt_version",
]


class RepoError(Exception):
    """Raised when a repository operation cannot be completed."""


@dataclass(frozen=True, slots=True)
class LlmProviderRecord:
    """Active LLM provider row as returned by :func:`get_active_llm_provider`."""

    id: str
    name: str
    kind: str
    base_url: str
    model: str
    api_key: str
    #: Blended price per 1M tokens (None = free or unknown; fake is always free).
    price_per_mtok: Decimal | None


def _embedding_literal(embedding: Sequence[float]) -> str:
    """Format an embedding as pgvector's text literal ``[1,2,3]``.

    Rounding to float32 precision keeps the literal byte-size predictable and
    matches the storage type (pgvector stores float4).
    """
    return "[" + ",".join(f"{value:.6g}" for value in embedding) + "]"


def ensure_source(conn: Connection, name: str) -> str:
    """Return the source id for ``name``, creating the row if missing.

    Idempotent: concurrent/repeated calls with the same name return the same id.
    """
    with conn.transaction():
        row = conn.execute(
            """
            INSERT INTO source (name) VALUES (%s)
            ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
            RETURNING id
            """,
            (name,),
        ).fetchone()
    if row is None:
        msg = f"ensure_source returned no row for {name!r}"
        raise RepoError(msg)
    return str(row[0])


def list_enabled_sources(conn: Connection) -> list[tuple[str, float]]:
    """Return ``(name, rate_limit_rps)`` for every enabled source, ordered by name.

    The collect stage iterates adapters in this order and hands each rate to
    its limiter (default 1 rps, migration 003). Disabled sources are skipped:
    the collect stage must not touch a source an operator switched off.
    """
    rows = conn.execute(
        """
        SELECT name, rate_limit_rps
        FROM source
        WHERE enabled
        ORDER BY name
        """
    ).fetchall()
    return [(str(name), float(rate)) for name, rate in rows]


def insert_raw_post(conn: Connection, post: RawPost, *, fetch_status: str = "new",
                    suspect_short: bool = False) -> str | None:
    """Insert a collected post; return its id, or None on URL duplicate.

    Idempotency contract: re-inserting a post with an already-known
    ``url_canon`` changes nothing and returns None, so re-running the collect
    stage never duplicates or mutates rows. ``fetch_status`` defaults to
    ``'new'``; ``suspect_short`` marks bodies suspiciously short for
    extraction.
    """
    with conn.transaction():
        row = conn.execute(
            """
            INSERT INTO raw_post
                (source_id, url_canon, url, title, body, kind,
                 published_at, fetch_status, suspect_short)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
            ON CONFLICT (url_canon) DO NOTHING
            RETURNING id
            """,
            (
                post.source_id,
                post.url_canon,
                post.url,
                post.title,
                post.text,
                post.kind,
                post.published_at,
                fetch_status,
                suspect_short,
            ),
        ).fetchone()
    return str(row[0]) if row is not None else None


def upsert_prompt_version(conn: Connection, name: str, version: int, body: str,
                          source: str) -> str:
    """Return the prompt_version id, inserting it when (name, version) is new.

    Re-registering the same (name, version) returns the existing id and never
    rewrites the stored body — bodies are immutable once shipped to a run.
    """
    with conn.transaction():
        row = conn.execute(
            """
            INSERT INTO prompt_version (name, version, body, source)
            VALUES (%s, %s, %s, %s)
            ON CONFLICT (name, version) DO UPDATE SET name = EXCLUDED.name
            RETURNING id
            """,
            (name, version, body, source),
        ).fetchone()
    if row is None:
        msg = f"upsert_prompt_version returned no row for {name!r} v{version}"
        raise RepoError(msg)
    return str(row[0])


def insert_pain(conn: Connection, pain: Pain, embedding: Sequence[float] | None,
                prompt_version_id: str) -> str:
    """Insert an extracted pain; return its id.

    ``embedding`` is the e5 vector of ``pain.body`` (or None when embeddings
    are disabled). The extract stage must only call this with pains whose
    ``quote`` is a verbatim substring of the source post text.
    """
    with conn.transaction():
        row = conn.execute(
            """
            INSERT INTO pain (raw_post_id, body, audience, quote, embedding,
                              prompt_version_id)
            VALUES (%s, %s, %s, %s,
                    CASE WHEN %s::text IS NULL THEN NULL
                         ELSE (%s::text)::vector END,
                    %s)
            RETURNING id
            """,
            (
                pain.source_post_id,
                pain.body,
                pain.audience,
                pain.quote,
                None if embedding is None else _embedding_literal(embedding),
                None if embedding is None else _embedding_literal(embedding),
                prompt_version_id,
            ),
        ).fetchone()
    if row is None:
        msg = "insert_pain returned no row"
        raise RepoError(msg)
    return str(row[0])


def upsert_cluster(conn: Connection, title: str, size: int,
                   kind_mix: dict[str, int]) -> str:
    """Create a cluster and return its id.

    Clusters are stage outputs recomputed per run, so there is no natural
    key to dedupe on: each clustering pass inserts fresh rows.
    """
    with conn.transaction():
        row = conn.execute(
            """
            INSERT INTO cluster (title, size, kind_mix)
            VALUES (%s, %s, %s::jsonb)
            RETURNING id
            """,
            (title, size, json.dumps(kind_mix)),
        ).fetchone()
    if row is None:
        msg = "upsert_cluster returned no row"
        raise RepoError(msg)
    return str(row[0])


def update_cluster_stats(conn: Connection, cluster_id: str, size: int,
                         kind_mix: dict[str, int]) -> None:
    """Recompute a cluster's size and kind mix after pain reassignment."""
    with conn.transaction():
        cursor = conn.execute(
            """
            UPDATE cluster SET size = %s, kind_mix = %s::jsonb WHERE id = %s
            """,
            (size, json.dumps(kind_mix), cluster_id),
        )
        if cursor.rowcount == 0:
            msg = f"cluster not found: {cluster_id}"
            raise RepoError(msg)


@dataclass(frozen=True, slots=True)
class ClusterInputPain:
    """One pain ready for clustering: id, embedding vector, post kind."""

    id: str
    embedding: list[float]
    kind: str


def list_cluster_input_pains(conn: Connection) -> list[ClusterInputPain]:
    """Return every pain with an embedding, in deterministic order.

    The cluster stage greedily groups these in order, so ``ORDER BY
    created_at, id`` makes repeated runs over the same input converge on
    the same partition. The pgvector text literal (``[1,2,3]``) is parsed
    back into plain floats here so the stage works on simple lists.
    """

    def _parse_vector(raw: object) -> list[float]:
        text = str(raw).strip().removeprefix("[").removesuffix("]")
        return [float(part) for part in text.split(",") if part]

    rows = conn.execute(
        """
        SELECT p.id::text, p.embedding, r.kind
        FROM pain p
        JOIN raw_post r ON r.id = p.raw_post_id
        WHERE p.embedding IS NOT NULL
        ORDER BY p.created_at, p.id
        """
    ).fetchall()
    return [
        ClusterInputPain(
            id=str(pain_id), embedding=_parse_vector(vector), kind=str(kind)
        )
        for pain_id, vector, kind in rows
    ]


def assign_pain_cluster(conn: Connection, pain_id: str, cluster_id: str) -> None:
    """Point one pain at its cluster (cluster stage reassignment)."""
    with conn.transaction():
        cursor = conn.execute(
            "UPDATE pain SET cluster_id = %s WHERE id = %s",
            (cluster_id, pain_id),
        )
        if cursor.rowcount == 0:
            msg = f"assign_pain_cluster: unknown pain id {pain_id}"
            raise RepoError(msg)


@dataclass(frozen=True, slots=True)
class ClusterScoreInput:
    """One unscored cluster plus the pain facts the rubric needs."""

    id: str
    size: int
    kind_mix: dict[str, int]
    sources: int
    first_seen: str
    last_seen: str
    bodies: list[str]


def list_clusters_without_score(conn: Connection) -> list[ClusterScoreInput]:
    """Return clusters that have no score yet, in deterministic order.

    The score stage runs the rubric prompt per cluster; clusters already
    carrying a score are skipped (re-scoring is explicit, not implicit).
    ``sources`` counts distinct feeds and the ``first_seen``/``last_seen``
    bounds come from the member posts via ``raw_post.created_at``.
    """
    rows = conn.execute(
        """
        SELECT c.id::text, c.size, c.kind_mix,
               count(DISTINCT p.raw_post_id) AS sources,
               min(r.created_at)::text, max(r.created_at)::text,
               array_agg(p.body ORDER BY p.created_at, p.id) AS bodies
        FROM cluster c
        JOIN pain p ON p.cluster_id = c.id
        JOIN raw_post r ON r.id = p.raw_post_id
        LEFT JOIN score s ON s.cluster_id = c.id
        WHERE s.id IS NULL
        GROUP BY c.id, c.size, c.kind_mix
        ORDER BY min(r.created_at), c.id
        """
    ).fetchall()
    result: list[ClusterScoreInput] = []
    for (cluster_id, size, kind_mix, sources, first_seen, last_seen,
         bodies) in rows:
        raw_mix: object = kind_mix
        mix = raw_mix if isinstance(raw_mix, dict) else json.loads(str(raw_mix))
        result.append(
            ClusterScoreInput(
                id=str(cluster_id),
                size=int(size),
                kind_mix={str(k): int(v) for k, v in dict(mix).items()},
                sources=int(sources),
                first_seen=str(first_seen),
                last_seen=str(last_seen),
                bodies=[str(body) for body in (bodies or [])],
            )
        )
    return result


def reset_cluster_assignment(conn: Connection) -> int:
    """Drop the previous clustering pass; return how many pains were reset.

    Clusters are stage outputs recomputed per run: the stage clears all
    assignments and deletes every cluster row before regrouping, so a
    repeated run produces the same partition with no orphan rows. The
    score stage does not exist yet (skeleton), so no score rows can
    reference deleted clusters; when score lands it must reset clusters
    through the pipeline order instead of this function.
    """
    with conn.transaction():
        count_row = conn.execute(
            "SELECT count(*) FROM pain WHERE cluster_id IS NOT NULL"
        ).fetchone()
        conn.execute("UPDATE pain SET cluster_id = NULL")
        conn.execute("DELETE FROM cluster")
    reset = int(count_row[0]) if count_row is not None else 0
    return reset


def update_pain_embedding(conn: Connection, pain_id: str,
                          embedding: Sequence[float]) -> None:
    """Store the e5 vector for an existing pain (embed stage backfill).

    Formats the vector as pgvector's text literal and casts it on the
    server side, same as :func:`insert_pain`. Raises :class:`RepoError`
    when the pain id is unknown.
    """
    with conn.transaction():
        row = conn.execute(
            """
            UPDATE pain SET embedding = (%s::text)::vector
            WHERE id = %s
            RETURNING id
            """,
            (_embedding_literal(embedding), pain_id),
        ).fetchone()
    if row is None:
        msg = f"update_pain_embedding: unknown pain id {pain_id}"
        raise RepoError(msg)


def insert_score(conn: Connection, score: Score) -> str:
    """Insert (or replace) the score for ``score.cluster_id``; return its id.

    One score per cluster: re-scoring the same cluster replaces the previous
    row (ON CONFLICT upsert), keeping the invariant enforced by the unique
    index on ``score.cluster_id``.
    """
    with conn.transaction():
        row = conn.execute(
            """
            INSERT INTO score (cluster_id, total, rationale_md, quotes_json)
            VALUES (%s, %s, %s, %s::jsonb)
            ON CONFLICT (cluster_id) DO UPDATE SET
                total = EXCLUDED.total,
                rationale_md = EXCLUDED.rationale_md,
                quotes_json = EXCLUDED.quotes_json
            RETURNING id
            """,
            (score.cluster_id, score.total, score.rationale_md,
             json.dumps(score.quotes)),
        ).fetchone()
    if row is None:
        msg = "insert_score returned no row"
        raise RepoError(msg)
    return str(row[0])


def create_run(conn: Connection, stages: dict[str, str] | None = None,
               stats: dict[str, int] | None = None) -> str:
    """Open a new pipeline run; return its id."""
    with conn.transaction():
        row = conn.execute(
            """
            INSERT INTO run (stages_json, stats_json)
            VALUES (%s::jsonb, %s::jsonb)
            RETURNING id
            """,
            (json.dumps(stages or {}), json.dumps(stats or {})),
        ).fetchone()
    if row is None:
        msg = "create_run returned no row"
        raise RepoError(msg)
    return str(row[0])


def update_run_stage(conn: Connection, run_id: str, stage: str, status: str,
                     stats_delta: dict[str, int] | None = None,
                     cost_delta: float = 0.0,
                     prompt_version_id: str | None = None) -> None:
    """Record stage progress on a run.

    ``stage``/``status`` merge into ``stages_json``; ``stats_delta`` adds into
    the per-run counters (e.g. ``{"bricked": 1}``); ``cost_delta`` accrues on
    ``run.cost`` so repeated stage calls accumulate spent money.
    ``prompt_version_id`` pins the prompt version used by the stage: it is
    recorded once via COALESCE (OR-semantics) - a later call passing None
    never overwrites an already recorded version, so a run stays
    reproducible even when retries race with a prompt bump.
    """
    with conn.transaction():
        cursor = conn.execute(
            """
            UPDATE run SET
                stages_json = stages_json || %s::jsonb,
                stats_json = _stats_merge(stats_json, %s::jsonb),
                cost = cost + %s,
                prompt_version_id = COALESCE(run.prompt_version_id,
                                             %s::uuid)
            WHERE id = %s
            """,
            (
                json.dumps({stage: status}),
                json.dumps(stats_delta or {}),
                cost_delta,
                prompt_version_id,
                run_id,
            ),
        )
        if cursor.rowcount == 0:
            msg = f"run not found: {run_id}"
            raise RepoError(msg)


def finish_run(conn: Connection, run_id: str) -> None:
    """Stamp ``finished_at`` on a run."""
    with conn.transaction():
        cursor = conn.execute(
            "UPDATE run SET finished_at = now() WHERE id = %s AND finished_at IS NULL",
            (run_id,),
        )
        if cursor.rowcount == 0:
            msg = f"run not found or already finished: {run_id}"
            raise RepoError(msg)


def upsert_llm_provider(conn: Connection, name: str, kind: str, base_url: str,
                        model: str, api_key: str, *, is_active: bool,
                        price_per_mtok: Decimal | float | None = None) -> str:
    """Insert or update a provider; enforce exactly one active row.

    ``api_key`` is stored only in the database (project convention); it never
    goes to logs or .env. Activating this provider atomically deactivates the
    previously active one — the partial unique index makes two active rows
    impossible, and the UPDATE below runs before the INSERT to avoid tripping
    it. ``price_per_mtok`` is an optional blended tariff per 1M tokens used by
    cost accounting; None (the default) means free or unknown.
    """
    with conn.transaction():
        if is_active:
            conn.execute(
                "UPDATE llm_provider SET is_active = false WHERE is_active",
            )
        row = conn.execute(
            """
            INSERT INTO llm_provider (name, kind, base_url, model, api_key,
                                      is_active, price_per_mtok)
            VALUES (%s, %s, %s, %s, %s, %s, %s)
            ON CONFLICT (name) DO UPDATE SET
                kind = EXCLUDED.kind,
                base_url = EXCLUDED.base_url,
                model = EXCLUDED.model,
                api_key = EXCLUDED.api_key,
                is_active = EXCLUDED.is_active,
                price_per_mtok = EXCLUDED.price_per_mtok
            RETURNING id
            """,
            (name, kind, base_url, model, api_key, is_active, price_per_mtok),
        ).fetchone()
    if row is None:
        msg = f"upsert_llm_provider returned no row for {name!r}"
        raise RepoError(msg)
    return str(row[0])


def get_active_llm_provider(conn: Connection) -> LlmProviderRecord | None:
    """Return the single active provider, or None when nothing is active."""
    row = conn.execute(
        """
        SELECT id, name, kind, base_url, model, api_key, price_per_mtok
        FROM llm_provider WHERE is_active
    """
    ).fetchone()
    if row is None:
        return None
    price = row[6]
    return LlmProviderRecord(
        id=str(row[0]), name=str(row[1]), kind=str(row[2]),
        base_url=str(row[3]), model=str(row[4]), api_key=str(row[5]),
        price_per_mtok=Decimal(price) if price is not None else None,
    )


def _run_from_row(row: tuple[object, ...]) -> Run:
    """Build a domain Run from a run-table row.

    Columns: (id, stages_json, stats_json, cost[, prompt_version_id]) - the
    optional trailing column is accepted so callers may select it when they
    care about the pinned prompt version. psycopg decodes ``jsonb`` columns
    to ``dict`` already; the ``str`` path covers drivers/tests that hand back
    raw text.
    """
    stages_raw, stats_raw, cost_raw = row[1], row[2], row[3]
    stages = stages_raw if isinstance(stages_raw, dict) else json.loads(str(stages_raw or "{}"))
    stats = stats_raw if isinstance(stats_raw, dict) else json.loads(str(stats_raw or "{}"))
    cost = float(cost_raw) if isinstance(cost_raw, (int, float, Decimal)) else 0.0
    prompt_version_id = str(row[4]) if len(row) > 4 and row[4] is not None else None
    return Run(
        stages={str(k): str(v) for k, v in stages.items()},
        stats={str(k): int(v) for k, v in stats.items()},
        cost=cost,
        id=str(row[0]),
        prompt_version_id=prompt_version_id,
    )


def get_run(conn: Connection, run_id: str) -> Run | None:
    """Return a run as a domain object, or None when the id is unknown."""
    row = conn.execute(
        """
        SELECT id, stages_json, stats_json, cost, prompt_version_id
        FROM run WHERE id = %s
        """,
        (run_id,),
    ).fetchone()
    return _run_from_row(row) if row is not None else None


def list_posts_pending_extract(conn: Connection,
                               limit: int | None = None) -> list[tuple[str, str]]:
    """Return ``(post_id, body)`` for posts awaiting pain extraction.

    A post is pending when it has no pain yet AND its fetch status is not
    terminal ('extracted' = processed with any outcome, 'failed' = hopeless
    answer, never retried; COALESCE covers rows written before status
    tracking). Both terminal states exist so repeated runs converge instead
    of re-sending the same posts to the LLM forever.
    """
    sql: LiteralString = """
        SELECT p.id::text, p.body
        FROM raw_post p
        LEFT JOIN pain ON pain.raw_post_id = p.id
        WHERE pain.id IS NULL
          AND COALESCE(p.fetch_status, 'new') IN ('new', 'fetched')
        ORDER BY p.created_at
    """
    if limit is not None:
        sql = cast(LiteralString, sql + f" LIMIT {int(limit)}")
    rows = conn.execute(sql).fetchall()
    return [(str(row[0]), str(row[1])) for row in rows]


def set_raw_post_fetch_status(conn: Connection, post_id: str,
                              status: str) -> None:
    """Set a post's ``fetch_status`` to a terminal value.

    The extract stage pins each attempted post: 'extracted' when the answer
    was processed (even with zero accepted pains), 'failed' when the answer
    is hopeless (unparseable JSON) and must not be retried. Raises
    :class:`RepoError` on an unknown post id or an invalid status value.
    """
    if status not in {"extracted", "failed"}:
        msg = f"invalid fetch_status: {status!r} (expected 'extracted' or 'failed')"
        raise RepoError(msg)
    with conn.transaction():
        cursor = conn.execute(
            "UPDATE raw_post SET fetch_status = %s WHERE id = %s",
            (status, post_id),
        )
        if cursor.rowcount == 0:
            msg = f"raw_post not found: {post_id}"
            raise RepoError(msg)


def table_counts(conn: Connection) -> dict[str, int]:
    """Return row counts for every pipeline table (status/dashboard view)."""
    tables = ("source", "raw_post", "pain", "cluster", "score", "run",
              "prompt_version", "llm_provider")
    counts: dict[str, int] = {}
    for table in tables:
        row = conn.execute(
            f"SELECT count(*) FROM {table}"  # table names are module constants
        ).fetchone()
        counts[table] = int(row[0]) if row is not None else 0
    return counts


def _main(data_dir: Path | None) -> int:
    """Smoke: fresh tmp cluster, migrations, repo round-trip, table counts."""
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s %(message)s")
    from datetime import UTC, datetime

    from idea_finder.core.canonical import canonical_url
    from idea_finder.db.bootstrap_pgserver import ensure_pgserver
    from idea_finder.db.migrate import apply_migrations

    handle = ensure_pgserver(data_dir)
    try:
        with handle.get_conn() as conn:
            applied = apply_migrations(conn)
            print("migrations applied:", applied)
            source_id = ensure_source(conn, "smoke-source")
            pv_id = upsert_prompt_version(conn, "extract_pains", 1, "PROMPT BODY", "file")
            post = RawPost(
                source_id=source_id,
                url_canon=canonical_url("https://example.com/a?utm_source=x"),
                url="https://example.com/a?utm_source=x",
                title="Example",
                text="Nobody can find a cheap plumber on weekends",
                published_at=datetime.now(tz=UTC),
                kind="demand",
            )
            post_id = insert_raw_post(conn, post)
            duplicate = insert_raw_post(conn, post)
            print("raw_post id:", post_id, "duplicate insert ->", duplicate)
            pain = Pain(
                source_post_id=post_id or "",
                body="No affordable weekend plumbing",
                audience="flat owners",
                quote="cheap plumber on weekends",
            )
            pain_id = insert_pain(conn, pain, [0.01 * (i % 7) for i in range(384)],
                                  pv_id)
            cluster_id = upsert_cluster(conn, "Plumbing", 1, {"demand": 1})
            conn.execute(
                "UPDATE pain SET cluster_id = %s WHERE id = %s", (cluster_id, pain_id)
            )
            update_cluster_stats(conn, cluster_id, 1, {"demand": 1})
            score_id = insert_score(
                conn,
                Score(cluster_id=cluster_id, total=7.5, rationale_md="ok",
                      quotes=["cheap plumber on weekends"]),
            )
            run_id = create_run(conn, {"collect": "running"})
            update_run_stage(conn, run_id, "collect", "done", {"bricked": 0}, 0.01)
            finish_run(conn, run_id)
            provider_id = upsert_llm_provider(
                conn, "fake", "fake", "", "fake-model", "sk-test", is_active=True
            )
            active = get_active_llm_provider(conn)
            counts = table_counts(conn)
            print("ids:", source_id, pv_id, post_id, pain_id, cluster_id,
                  score_id, run_id, provider_id)
            print("active provider:", active.name if active else None)
            print("table_counts:", counts)
        return 0
    except Exception as e:
        logger.error("repo smoke failed: %s", e)
        raise


if __name__ == "__main__":
    directory = Path(sys.argv[1]) if len(sys.argv) > 1 else None
    sys.exit(_main(directory))
