"""Domain models flowing through the pipeline stages.

Data flow: sources produce ``RawPost``, LLM extraction turns posts into
``Pain``, clustering groups pains into ``Cluster``, scoring rates clusters
and yields ``Score``, and every pipeline execution is tracked as a ``Run``.

Row IDs (UUIDv7) are generated by the database, so ``id`` stays optional
here: stages pass unsaved instances around, and ``db/repo.py`` fills the
ID once a row is written.
"""

from dataclasses import dataclass
from datetime import datetime
from typing import Literal

__all__ = ["Cluster", "Pain", "PostKind", "RawPost", "Run", "Score"]

PostKind = Literal["demand", "complaint", "discussion"]

# Runtime mirror of the PostKind values; the type checker enforces that every
# entry here is a valid PostKind, so the domain contract cannot drift from
# the Literal type.
_VALID_KINDS: tuple[PostKind, ...] = ("demand", "complaint", "discussion")


@dataclass(frozen=True, slots=True)
class RawPost:
    """A post collected from a source, in canonical form.

    ``url_canon`` is the canonicalized URL used for deduplication (see
    ``core.canonical``); ``url`` is the original one as fetched. ``kind``
    is a mandatory domain classification, validated at construction.
    """

    source_id: str
    url_canon: str
    url: str
    title: str
    text: str
    published_at: datetime | None
    kind: PostKind
    id: str | None = None

    def __post_init__(self) -> None:
        if self.kind not in _VALID_KINDS:
            msg = f"kind must be one of {', '.join(_VALID_KINDS)}, got {self.kind!r}"
            raise ValueError(msg)


@dataclass(frozen=True, slots=True)
class Pain:
    """A user pain extracted from a raw post by the LLM.

    ``quote`` must be a verbatim substring of the source text; the extract
    stage validates containment and bricks the record otherwise.
    """

    source_post_id: str
    body: str
    audience: str
    quote: str
    id: str | None = None


@dataclass(frozen=True, slots=True)
class Cluster:
    """A group of semantically similar pains.

    ``kind_mix`` counts pains by ``PostKind`` inside the cluster, e.g.
    ``{"demand": 4, "complaint": 1}``.
    """

    title: str
    size: int
    kind_mix: dict[str, int]
    id: str | None = None


@dataclass(frozen=True, slots=True)
class Score:
    """Rubric-based assessment of a cluster for the Russian market.

    ``rationale_md`` is a markdown justification; ``quotes`` holds the
    verbatim pain quotes the score is grounded in.
    """

    cluster_id: str
    total: float
    rationale_md: str
    quotes: list[str]
    id: str | None = None


@dataclass(frozen=True, slots=True)
class Run:
    """Progress and cost bookkeeping for one pipeline execution.

    ``stages`` maps stage name to status (e.g. ``{"collect": "done"}``);
    ``stats`` carries per-run counters such as bricked records.
    ``prompt_version_id`` pins the prompt_version the extract stage used,
    making the run reproducible (NULL for legacy runs).
    """

    stages: dict[str, str]
    stats: dict[str, int]
    cost: float
    id: str | None = None
    prompt_version_id: str | None = None
